### ISSUE TITLE
いいね

### ISSUE THREAD

**Issue by daddygongon** [void-hoge/AtCrawler-rb#1]
publicだったので，だいぶ前に見てて，これは使うなと感心していました．
AtCoderのAPIの詳細がわからないのですが，QiitaだとPagingという機構が組み込まれていて，
一個づつを落とすとすぐにlimitになるのですが，pagerを適切に指定すると相当数を一括ダウンロードできたりします．

**Comment by void-hoge** [comment]
私の知る限り、AtCoderにはAPIと呼べるようなリッチな仕組みは存在せず、このプロジェクトはprimitiveなgetとpostだけで実装してあります。(ログイン以外はwgetでも実装できる。)
コンテスト中、全ての参加者に一定のレイテンシで結果を返すため、秒間リクエスト数や分間リクエスト数がかなり厳しく制限されているような感じです。
そのため、アクセス制限を回避する方法は間を空ける以外に多分なさそうに思います。
